export class SenalesItem {
    cod_senal:number;
    cod_org:number;
    cod_esp:number;
    cod_cop:number;
    cod_etiqueta:number;
    desc_senal:string;
    enlace:string;
    fecha_hora:Date;
    nombre_completo:string;
    ind_fech_gest:boolean;
    titulo:string;
    img_senal:string;
    cantidad_comentarios:number;
    me_gustas:number;
    me_ha_gustado:boolean;
    desc_etiqueta:string;
    cod_usuario:string;
}
